# Generated by Django 5.1.1 on 2024-09-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizações', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('organizacoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizações.organizações')),
            ],
        ),
    ]
