# Generated by Django 5.1.1 on 2024-09-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='nome',
            new_name='estoque',
        ),
    ]
