# Generated by Django 5.1.1 on 2024-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_rename_nome_estoque_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='estoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
