# Generated by Django 5.1.1 on 2024-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0003_remove_estoque_estoque_estoque_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='nome',
        ),
        migrations.AddField(
            model_name='estoque',
            name='estoque',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
