# Generated by Django 5.1.1 on 2024-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0004_remove_estoque_nome_estoque_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='estoque',
            new_name='nome',
        ),
    ]
