# Generated by Django 5.1.1 on 2024-09-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0006_rename_nome_estoque_estoque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
