# Generated by Django 5.1.1 on 2024-10-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
