# Generated by Django 5.1.1 on 2024-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_eventos_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='agenda',
        ),
    ]
