# Generated by Django 5.1.1 on 2024-10-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contatos', '0001_initial'),
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='Contatos.contatos')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='Eventos.eventos')),
            ],
        ),
    ]
