# Generated by Django 5.1.1 on 2024-10-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
        ('Usuario', '0003_remove_colaborador_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='contatos',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='eventos',
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.colaborador'),
        ),
    ]
