# Generated by Django 5.1.1 on 2024-10-27 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_remove_agenda_contatos_remove_agenda_eventos_and_more'),
        ('Usuario', '0003_remove_colaborador_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='Usuario.colaborador'),
        ),
    ]
