# Generated by Django 5.1.1 on 2024-10-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_alter_agenda_user'),
        ('Usuario', '0003_remove_colaborador_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_associada', to='Usuario.colaborador'),
        ),
    ]
