# Generated by Django 5.1.1 on 2024-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_alter_agenda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='user',
        ),
    ]
