# Generated by Django 5.1.1 on 2024-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_remove_agenda_user'),
        ('Contatos', '0003_remove_contatos_agenda_contatos_colaborador'),
        ('Eventos', '0003_remove_eventos_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
