# Generated by Django 5.1.1 on 2024-11-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizações', '0001_initial'),
        ('Produto', '0015_alter_produto_data_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizações.organizações')),
                ('produtos', models.ManyToManyField(through='Pedidos.PedidoProduto', to='Produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='numero_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedidos.pedidos'),
        ),
    ]
