# Generated by Django 5.1.1 on 2025-01-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('versão', models.CharField(max_length=20)),
                ('instalado', models.BooleanField(default=False)),
                ('dependencias', models.JSONField(default=list)),
                ('created_At', models.DateField(default=datetime.datetime(2025, 1, 22, 15, 59, 7, 98688))),
                ('updated_At', models.DateField(default=datetime.datetime(2025, 1, 22, 15, 59, 7, 99688))),
            ],
        ),
    ]
