# Generated by Django 5.1.1 on 2025-01-23 19:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('versão', models.CharField(max_length=20)),
                ('instalado', models.BooleanField(default=False)),
                ('dependencias', models.JSONField(default=list)),
                ('arquivo_pacote', models.FileField(upload_to='app_pacotes/')),
                ('publicado', models.BooleanField(default=False)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='market',
            old_name='instalado',
            new_name='destaque',
        ),
        migrations.RemoveField(
            model_name='market',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='market',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='market',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='market',
            name='versão',
        ),
        migrations.AddField(
            model_name='market',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='market',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='market',
            name='aplicativos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='Market.app'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cod_autorizacao', models.CharField(max_length=15, unique=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Market.developer'),
        ),
    ]
