# Generated by Django 5.1.1 on 2025-01-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_alter_developer_options_alter_developer_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='developer', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='developer_permission', to='auth.permission'),
        ),
    ]
