# Generated by Django 5.1.1 on 2025-01-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_alter_developer_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='cod_autorizacao',
        ),
    ]
