# Generated by Django 5.1.1 on 2025-01-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_remove_developer_cod_autorizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='nome_empresa',
        ),
    ]
