# Generated by Django 5.1.1 on 2025-01-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_remove_developer_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
