# Generated by Django 5.1.1 on 2025-01-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_developer_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='telefone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
