# Generated by Django 5.1.1 on 2025-01-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_alter_app_autor_delete_developer'),
        ('Usuario', '0019_remove_developer_is_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.developer'),
        ),
    ]
