# Generated by Django 5.1.1 on 2025-01-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_alter_app_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='versão',
            new_name='versao',
        ),
    ]
