# Generated by Django 5.1.1 on 2025-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0011_rename_versão_app_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
