# Generated by Django 5.1.1 on 2025-01-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_app_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='approved_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
