# Generated by Django 5.1.1 on 2025-01-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0014_alter_app_approved_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='arquivo_pacote',
            new_name='zip_file',
        ),
    ]
