# Generated by Django 5.1.1 on 2025-01-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0015_rename_arquivo_pacote_app_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='zip_file',
            field=models.FileField(upload_to=''),
        ),
    ]
