# Generated by Django 5.1.1 on 2025-01-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0016_alter_app_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='approved_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='zip_file',
            field=models.FileField(upload_to='media/apps/'),
        ),
    ]
