# Generated by Django 5.1.1 on 2025-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0017_alter_app_approved_status_alter_app_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='approved_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], max_length=10),
        ),
    ]
