# Generated by Django 5.1.6 on 2025-02-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0018_alter_app_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='approved_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Pendente', max_length=10),
        ),
    ]
