# Generated by Django 5.1.1 on 2024-10-24 00:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizações', '0001_initial'),
        ('Produto', '0003_alter_produto_data_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=1, max_digits=100000000)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('data_venda', models.DateField(default=datetime.datetime(2024, 10, 24, 0, 24, 17, 11820, tzinfo=datetime.timezone.utc))),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizações.organizações')),
                ('produto', models.ManyToManyField(to='Produto.produto')),
            ],
        ),
    ]
