# Generated by Django 5.1.1 on 2024-10-25 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 25, 3, 42, 54, 112331, tzinfo=datetime.timezone.utc)),
        ),
    ]
