# Generated by Django 5.1.1 on 2024-11-14 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0002_remove_vendas_produto_remove_vendas_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 17, 44, 59, 683598, tzinfo=datetime.timezone.utc)),
        ),
    ]
