# Generated by Django 5.1.1 on 2024-10-27 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0007_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 27, 3, 7, 35, 728429, tzinfo=datetime.timezone.utc)),
        ),
    ]
