# Generated by Django 5.1.1 on 2024-10-27 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0009_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 27, 4, 0, 3, 771125, tzinfo=datetime.timezone.utc)),
        ),
    ]
