# Generated by Django 5.1.1 on 2024-10-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0010_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 28, 20, 44, 57, 914095, tzinfo=datetime.timezone.utc)),
        ),
    ]
