# Generated by Django 5.1.1 on 2024-10-30 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0012_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 3, 15, 0, 579354, tzinfo=datetime.timezone.utc), verbose_name='data_venda'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, max_digits=100000000, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=100000000, verbose_name='valor_total'),
        ),
    ]
