# Generated by Django 5.1.1 on 2024-10-30 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0013_alter_vendas_data_venda_alter_vendas_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 17, 48, 6, 613172, tzinfo=datetime.timezone.utc), verbose_name='data_venda'),
        ),
    ]
