# Generated by Django 5.1.1 on 2024-11-12 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0015_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 1, 43, 18, 221040, tzinfo=datetime.timezone.utc), verbose_name='data_venda'),
        ),
    ]
