# Generated by Django 5.1.1 on 2024-11-12 22:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0004_alter_contatos_colaborador'),
        ('Pedidos', '0001_initial'),
        ('Vendas', '0016_remove_vendas_quantidade_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='produto',
        ),
        migrations.AddField(
            model_name='vendas',
            name='numero_pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='Pedidos.pedidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contatos.contatos'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 22, 38, 24, 60190, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
