# Generated by Django 5.1.1 on 2024-11-12 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0017_remove_vendas_produto_vendas_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 22, 50, 43, 41791, tzinfo=datetime.timezone.utc)),
        ),
    ]
