# Generated by Django 5.1.1 on 2024-11-12 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0018_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 22, 51, 15, 18378, tzinfo=datetime.timezone.utc)),
        ),
    ]
