# Generated by Django 5.1.1 on 2024-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
