# Generated by Django 5.1.1 on 2024-11-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_colaborador_cargo_alter_colaborador_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='sobrenome',
        ),
    ]
