# Generated by Django 5.1.1 on 2024-10-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_colaborador_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='agenda',
        ),
    ]
