# Generated by Django 5.1.1 on 2024-11-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_remove_colaborador_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='ultimo_login',
        ),
    ]
