# Generated by Django 5.1.1 on 2024-11-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_colaborador_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='empresa',
        ),
    ]
