# Generated by Django 5.1.1 on 2024-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_remove_colaborador_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
