# Generated by Django 5.1.1 on 2024-11-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_endereco_alter_colaborador_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
