# Generated by Django 5.1.1 on 2024-11-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0002_setor_cargo'),
        ('Usuario', '0010_colaborador_empresa_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='Organização.empresa'),
        ),
    ]
