# Generated by Django 5.1.1 on 2024-11-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0003_alter_cargo_setor_alter_setor_empresa'),
        ('Usuario', '0011_alter_colaborador_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='Organização.empresa'),
        ),
    ]
