# Generated by Django 5.1.1 on 2024-12-02 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0006_alter_cargo_nome_cargo'),
        ('Usuario', '0012_alter_colaborador_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='Organização.cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='Organização.setor'),
        ),
    ]
