# Generated by Django 5.1.1 on 2025-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0014_alter_colaborador_cargo_alter_colaborador_cpf_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='colaborador_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='colaborador_permission_set', to='auth.permission'),
        ),
    ]
