# Generated by Django 5.1.1 on 2025-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0016_alter_colaborador_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
