# Generated by Django 5.1.1 on 2025-01-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0018_remove_colaborador_is_developer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='is_developer',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
