# Generated by Django 5.1.1 on 2024-11-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=9, null=True, verbose_name='Inscrição Estadual')),
                ('im', models.CharField(blank=True, max_length=11, null=True, verbose_name='Inscrição Municipal')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('type_organizacao', models.CharField(choices=[('Matriz', 'Matriz'), ('Filial', 'Filial')], max_length=50, verbose_name='Tipo de Organização')),
            ],
        ),
    ]
