# Generated by Django 5.1.1 on 2024-11-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organização.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organização.setor')),
            ],
        ),
    ]
