# Generated by Django 5.1.1 on 2024-11-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0002_setor_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='Organização.setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='Organização.empresa'),
        ),
    ]
