# Generated by Django 5.1.1 on 2024-11-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0003_alter_cargo_setor_alter_setor_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='setor',
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ManyToManyField(related_name='cargos', to='Organização.setor'),
        ),
    ]
