# Generated by Django 5.1.1 on 2024-12-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0004_remove_cargo_setor_cargo_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Setor'),
        ),
    ]
