# Generated by Django 5.1.1 on 2024-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0005_alter_setor_nome_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cargo'),
        ),
    ]
