# Generated by Django 5.1.1 on 2024-12-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organização', '0006_alter_cargo_nome_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='setor',
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='Organização.setor'),
            preserve_default=False,
        ),
    ]
