# Generated by Django 5.1.1 on 2024-09-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('KG', 'Kilograma'), ('UN', 'Unidade'), ('LT', 'Litro'), ('CX', 'Caixa'), ('MT', 'Metro')], max_length=5)),
                ('quantidade', models.DecimalField(decimal_places=1, max_digits=10)),
                ('estoque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='Estoque.estoque')),
            ],
        ),
    ]
