# Generated by Django 5.1.1 on 2024-09-27 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_joined',
            field=models.DateField(default=datetime.date(2024, 9, 27), max_length=datetime.date(2024, 9, 27)),
        ),
    ]
