# Generated by Django 5.1.1 on 2024-09-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='estoque_id',
        ),
    ]
