# Generated by Django 5.1.1 on 2024-10-24 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0002_produto_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_joined',
            field=models.DateField(default=datetime.date(2024, 10, 23), max_length=datetime.date(2024, 10, 23)),
        ),
    ]
