# Generated by Django 5.1.1 on 2024-11-13 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0017_alter_produto_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_joined',
            field=models.DateField(default=datetime.datetime(2024, 11, 13, 21, 29, 49, 956057, tzinfo=datetime.timezone.utc), max_length=datetime.datetime(2024, 11, 13, 21, 29, 49, 956057, tzinfo=datetime.timezone.utc)),
        ),
    ]
