# Generated by Django 5.1.1 on 2024-11-14 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0022_alter_produto_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_joined',
            field=models.DateField(default=django.utils.timezone.now, max_length=django.utils.timezone.now),
        ),
    ]
