# Generated by Django 5.1.1 on 2024-10-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('is_Customer', models.BooleanField(default=False)),
                ('is_Partner', models.BooleanField(default=False)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
