# Generated by Django 5.1.1 on 2024-10-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_remove_agenda_contatos_remove_agenda_eventos_and_more'),
        ('Contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Agenda.agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contatos',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
