# Generated by Django 5.1.1 on 2024-10-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0002_contatos_agenda_alter_contatos_nome'),
        ('Usuario', '0003_remove_colaborador_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='agenda',
        ),
        migrations.AddField(
            model_name='contatos',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.colaborador'),
            preserve_default=False,
        ),
    ]
