# Generated by Django 5.1.1 on 2024-10-28 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0003_remove_contatos_agenda_contatos_colaborador'),
        ('Usuario', '0003_remove_colaborador_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='Usuario.colaborador'),
        ),
    ]
